### ISSUE TITLE
Navigation error on all proxies

### ISSUE THREAD

**Issue by iLinked1337** [gajus/puppeteer-proxy#5]
I'm trying to implement puppeteer-proxy into my project, but even on valid proxies it gives me this error:
```
(node:26252) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
    at async FrameManager.navigateFrame (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\FrameManager.js:94:17)
    at async Frame.goto (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\FrameManager.js:406:12)
    at async Page.goto (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\Page.js:675:12)
    at async C:\Users\edhbu\source\repos\*******\ok.js:22:5
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\Page.js:675:49)
    at Page.<anonymous> (C:\Users\edhbu\source\repos\*******\node_modules\puppeteer\lib\helper.js:112:23)
    at C:\Users\edhbu\source\repos\*******\ok.js:22:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

My code is:
```js
const puppeteer = require('puppeteer');
const { proxyRequest } = require('puppeteer-proxy');

(async() => {
    const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();

    await page.setRequestInterception(true);
    page.on('request', async req => {
        if (req.url().startsWith('http')) {
            await proxyRequest({
                page,
                proxyUrl: 'http://localhost:3000',
                request: req
            });
        }
    });

    await page.goto('https://google.com');
})();
```

**Comment by gajus** [comment]
As the error says, it is a timeout. Debug why proxies are timing out. Doesn't seem like `puppeteer-proxy` bug at the surface.
